### ISSUE TITLE
[Galleries] `index` is not taken into account, and sometimes as you switch images, the current one is stretched/shrinked horizontally to the width of the next one

### ISSUE THREAD

**Issue by darkred** [tophf/mpiv#122]
#### Summary:

I have noticed two issues with galleries:
- hovered thumbnail is ignored not used as index
-  as your switch to the next image, the current one is stretched/shrinked horizontally to the width of the next one.

#### Steps to reproduce the bug

- Install this rule: ([ref](https://github.com/tophf/mpiv/issues/25#issuecomment-744025378))

    ```json
    {"d": "twilightsite.com",
     "e": "td > a:first-child",
     "s": "gallery",
     "g": {
      "image": "td > a:first-child",
      "index": "return node.href"
     }
    }
    ``` 

- Open http://www.twilightsite.com/fantasy/Old/Royo/Royo.html
- Click "Disable cache" in devtools 'Network' in order to make it occur consistently.
- Mouseover 2nd thumb: notice that the 1st image is displayed full-size instead
- Now scroll until and then back and forth between 4th and 5th thumbs: notice that every time you switch images, the current full size is momentarily stretched horizontally to the width of the next/previous one

<details>
<summary>Screen capture:</summary>

![](https://github.com/user-attachments/assets/5b45aa80-500c-4000-a90c-279f7dc604c0)

</details>

#### Environment
 - Browser: Chrome 127, Firefox 129
 - Script manager: TM beta 5.3.6207, VM beta 2.20.2
 - MPIV version: 1.4.1

**Comment by tophf** [comment]
Should be fixed now.

**Comment by darkred** [comment]
Yes, it's fixed. Thanks a lot for your quick response!

**Comment by darkred** [comment]
Hi @tophf .
Unfortunately I see that it still occurs. If you reproduce the STR from OP, disable cache in Network devtools, mouseover 4nd thumb (wait for full image popup to complete) and scroll to 5th image, the issue occurs consistently. Tested with latest TM beta 5.3.6211 and VM beta 2.20.5.

<details>
<summary>Screen capture:</summary>

![](https://github.com/user-attachments/assets/a9db9adb-48f4-458a-b944-5c04d6bad637)
</details>

**Comment by darkred** [comment]
Thanks a lot once again! I just noticed one thing: with the latest changes, now there's a white placeholder initially, and then the image is gradually loaded. I suppose this is unavoidable as part of the fix, or could it be avoided?

<details>
<summary>Screen capture:</summary>

![](https://github.com/user-attachments/assets/1182df95-f170-4b11-8b24-1bdd262bda13)
</details>

**Comment by tophf** [comment]
Is it Firefox? Looks like that ancient bug with images that always existed. I tried circumventing it by reusing the image, but it caused the problems with proportions.

**Comment by tophf** [comment]
You can enable `Wait for complete image` in MPIV options.

**Comment by darkred** [comment]
It occurs in both Chrome and Firefox, stable and even in nightly/canary. Ok, I see.
Thanks for the tip, and again for the help!

**Comment by tophf** [comment]
It doesn't occur for me in Chrome.

**Comment by tophf** [comment]
I guess it's a bug in your GPU driver. Try installing a newer or a much older version.

**Comment by darkred** [comment]
> I guess it's a bug in your GPU driver. Try installing a newer or a much older version.

My GPU is an NVidia GTX 1660Ti. The latest drivers 561.09 are very recent,  released just two weeks ago. I'd prefer not to install an older driver because the current one supports a game I'm currently playing and another I'm interested in.

**Comment by darkred** [comment]
I just found that the issue with the white border/placeholder is essentially the same as #75 of four years ago (also reported by me four years ago, I had totally forgotten about it, sorry).

Anyway, regarding Firefox, there's this old and and unfortunately still open bugzilla bug [1556156 White background during image loading](https://bugzilla.mozilla.org/show_bug.cgi?id=1556156) which I had mentioned in here https://github.com/tophf/mpiv/issues/75#issuecomment-942297323 .
In other words, in Firefox the white border issue always occurs, regardless of your latest commit. Sorry it skipped my attention.

But, regarding Chrome, is doesn't seem to be a browser bug: it started occurring with your https://github.com/tophf/mpiv/commit/e0b10f7d447ad3b7a17f653c237cfd9065be90fb commit
It didn't occur with commit https://github.com/tophf/mpiv/commit/e0b10f7d447ad3b7a17f653c237cfd9065be90fb

Having in devtools 'Network': 
 - tick "Disable cache", as before, and
 - enable Throttling to the slowest available preset, 3G 

the white placeholder issue occurs for me consistently with Chrome. 

I understand that this must be a necessity in order not to have the problem with proportions.

**Comment by tophf** [comment]
> it started occurring with your e0b10f7d447ad3b7a17f653c237cfd9065be90fb commit

This commit restored the ancient behavior, i.e. a new image is created when advancing in a gallery, so it is a bug in the browser that you reported in #75 and I still can't reproduce it. I'll try to understand the difference between the code back then, which fixed it for you, and now...

> the white placeholder issue when mouseover 4th thumb occurs for me consistently with Chrome

Definitely a bug in Chrome or in GPU driver. Doesn't occur for me.

**Comment by tophf** [comment]
Regarding my "I'll try to understand the difference between the code back then, which fixed it for you, and now...", I've looked at the code and if I restore that, there'll be a bug in proportions.

**Comment by tophf** [comment]
BTW I've never seen it in Chrome, and I can't even find any mentions of such a bug in Chrome in the internet...

**Comment by tophf** [comment]
Try adding `#mpiv-popup.mpiv-show { background:none!important }` to Custom CSS in options.

**Comment by darkred** [comment]
The combination of these two rules completely solved the issue in Chrome! Thanks a lot!

<details>
<summary>Screen capture:</summary>

![Animation99~~~4](https://github.com/user-attachments/assets/a7154ebb-b181-4bf9-b872-6b678a7bd00a)</details>
