### ISSUE TITLE
Border styling interferes with scaling of popup

### ISSUE THREAD

**Issue by Ryujinra** [tophf/mpiv#15]
Not sure if this is considered unsupported but it still seems like unintended behavior: if you add a small border using the css border property for the popup in the script, or use the css styling in the configuration window, the popup will have empty space below it which increases as you increase the border size. With `fit to window` enabled, It is visible even with a 1px border, but a 10px border illustrates the issue better. Besides this issue with extraneous padding on the bottom of the popup, the border seems to be applied properly and evenly around the image.

EDIT: The behavior is different for large images scaled down and smaller images scaled up: for smaller images scaled to the window, the bottom of the popup is actually _cut off_.

I guess that ultimately the scaling algorithm just needs to take into account the added width and height from the popup border before doing its work?

**Comment by tophf** [comment]
I've reworked scaling and seemingly fixed this bug.

**Comment by Ryujinra** [comment]
Almost perfect; there seems to be a small horizontal rounding error issue. Visit [instagram.com/instagram](https://www.instagram.com/instagram). Put border at `5px`, you'll see there is a 1px white strip on the outer side of the right border of some images. Put border at `10px`, and you'll see the 1px white strip on the inner side of the right border on those same images.

**Comment by tophf** [comment]
Can't repro. Must be your dpi thing. No idea how to fix it so I've just removed rounding, see if it works for you.

**Comment by Ryujinra** [comment]
Yes, it is related because if I don't use Firefox DPI scaling at all, there is no issue. 

With the new commit, the behavior doesn't change based on the border size any more, but ALL border sizes are now off by one pixel on the right side, and when zooming the image, the right border changes by one pixel (sometimes it is correct, other times I see a white strip).

Honestly, we should just revert it to how it was before - at least previously, the <4px case worked fine, which is most important, and there only issues in certain border width ranges higher than that.

**Comment by tophf** [comment]
Well, I don't have a preference on this since I believe this is a bug in FF so let's revert. Maybe you can find a different dpi value that hides the bug.

**Comment by Ryujinra** [comment]
It is possibly an issue with Firefox's fractional scaling implementation (in fact, a lot of my issues might be due to that), since a DPI scale of 2 doesn't seem to trigger it. But it's better the way it was since it is easier to find DPI values that don't cause issues with the old scaling implementation than it is with the new one.

**Comment by tophf** [comment]
Try `outline` instead of `border`.

**Comment by Ryujinra** [comment]
With `outline`, the bottom border doesn't appear even without Firefox DPI scaling on. With Firefox DPI scaling, the bottom border still isn't there, and there is a `1px` empty space at the top of the image at certain DPIs.

But no white strips on the right side anymore like with `border`.

**Comment by tophf** [comment]
Yep, I broke outline calculations...

**Comment by tophf** [comment]
Should be fixed now.

**Comment by Ryujinra** [comment]
`outline` does have the bottom border now. Still have a 1px space above the top border at some outline sizes, but I'm pretty convinced this is some bug in Firefox.

Now both `outline` and `border` work for me with 1px size; any advantage to using outline?

Also, are we able to detect `zoomed beyond window size` status with css, or maybe you could just hardcode the following behavior:  the border/outline should probably be made invisible when zoomed beyond the confines of the viewport (so the sides don't have borders when you zoom in beyond `fit-to-window`).

**Comment by Ryujinra** [comment]
EDIT: On second thought, that behavior might not always be desired; if you are using a thin border as a line of demarcation between image content and page content, you'd probably still want to see, e.g. the horizontal borders, even when the vertical parts of the image are beyond the viewport. If we could somehow reference that status using CSS styling, then anyone could handle it as they see fit.

**Comment by tophf** [comment]
>Is there an advantage to using outline over border?

No.

>detect "zoomed beyond window size" status with css 

No such thing at the moment, but it'd be easy to toggle some class name like `mpiv-exceeds-width` and `mpiv-exceeds-height`. Currently mpiv assumes the styles don't change while zooming to avoid a costly getComputedStyle each time zoom changes. OTOH, I could just allow zooming to be imprecise (not a big problem I guess).

>the border/outline should probably be made invisible 

Frankly, I don't see why, but I no longer understand the appeal of a border either as I've been removing it in mpiv for years. There was a period at the beginning of mpiv when I used a border but then I decided it's visually fussy and switched to a shadow which is conceptually much more suiting in my view as it kinda makes the popup float above the page.

**Comment by Ryujinra** [comment]
I use a 0.5px solid black border now; I didn't use a border for a long time, but found a very tiny border allows me to see better where image content ends when there is a lot of white in the image and the page, or the page is very messy or has a lot of other images. For me, a dropshadow draws my attention away too much even when it's small, but different strokes for different folks and that's why CSS styling is so useful ;).

I've changed my mind on making the border invisible while zooming; I guess that it could be nice as a low prio feature since you could do interesting animation things, but my original thought was it didn't seem right when you would zoom past the confines of the viewport in one direction and you still had, say, the side borders, but the top ones were now clipped from zooming. This particular case may not see a lot of use but maybe there are other uses for having those class names.

**Comment by tophf** [comment]
I still don't understand so you'll have to implement it yourself in a way that makes sense to you and present a convincing use case.
