### ISSUE TITLE
Some issues and suggestions

### ISSUE THREAD

**Issue by darkred** [tophf/mpiv#23]
I've noticed the following 3 issues (all related to Steam pages):
(tested with latest MPIV in TM/VM with Chrome)

---

1. When a rule has applied some replace() to a thumbnail in order to create the full size image for the popup, **shouldn't the black bar on top contain the filename of the popup image**, instead of the filename of the thumbnail?

   e.g. I have the following rule (for Steam pages like [this one](https://store.steampowered.com/app/952060/RESIDENT_EVIL_3/)) :

   ```json
   {"d": "store.steampowered.com",
    "r": "steamcdn-a\\.akamaihd\\.net",
    "s": "return node.src.replace(/\\.[x0-9]+/,'').replace(/\\?t=[0-9]+/,'')"
   }
   ```
   of which the `s` part converts thumbnail URLs as follows: 
*(I've shortened them)*

   ```
   from: https://___/ss_77eda710487b89293f109cf7dcf96b4ffab0d1a1.116x65.jpg?t=1583732360
   to:   https://___/ss_77eda710487b89293f109cf7dcf96b4ffab0d1a1.jpg
   ```

   When I hover such a thumbnail, I see the filename of the thumbnail in the bar:
   ![2020-03-18_172650](https://user-images.githubusercontent.com/723651/76983378-fc9c8f00-6945-11ea-9d34-e2b8d95b6ce8.jpg)
   even though, the converted URL is what's displayed in the popup, i.e. without the `.116x65` part

---

2. For any rule (especially the above), as I mousover any thumbnail,
   the level is initially displayed as `NaN%` (momentarily) and then it's replaced with the actual zoom level. **Could this be avoided??**

---

3. In a lot of cases, Steam game pages take way too long to fully load, I've seen 20 sec or more.
   e.g. try to open to a new tab for the first time any link from [this list](https://store.steampowered.com/explore/upcoming/).

   During that time, using the above rule, there's no popup as I mouseover any thumbnail - only a spinning cursor, and popup only works after (or close to the point when) the page has fully load.

   **Could it be improved?** 

   *If it helps, I have enabled the MPIV setting to "Start preloading immediately"*.

---

- A feature suggestion, please:
a filter checkbox in MPIV settings, which, when checked, 
to **only list those custom rules that apply to the current page**
(either their `d` or `u` attribute matches the current page domain, 
or (if the rule only has `r`) the relevant regex to match at least one link/thumbnail element in the page).
I find myself looking for such a filter all the time 🙂 
*I hope you like my idea and what I ask is doable!*

**Comment by tophf** [comment]
1. fixed.
2. couldn't repro, I've only seen it a few weeks ago and fixed it then; can you see it with default options (first export your current options, then import `{}`)?
3. mpiv loads when the page loads and for 99.9% of sites it's fine so I won't be changing that because a) loading scripts at page start slows it down even if for a bit, the more such scripts are loaded the more it slows down, and b) you can set `run-at` mode of the script in your manager to `document-start` manually.
4. Simply copypaste the site name in the filter input, I don't want to add an extremely rarely used feature for a few people who write rules more than once a month. The script is too big already. You can set open mpiv code in devtools debugger and set a breakpoint after [`customRules` line](https://github.com/tophf/mpiv/blob/1b48e00739cecc23fae5c7eeae88956cd3f35338/script.user.js#L1098), then click the Apply button in config dialog and see the contents of the variable when the breakpoint is hit.

**Comment by darkred** [comment]
Thanks for the detailed reply

1. Thank you.

2. Yes, it occurs consistently: I have just confirmed it only occurs when I enable "Start preloading immediately" in MPIV settings.
   *Tested with a fresh Chrome profile, with only TM/VM and the script installed,
   reseting settings (`{}`) and then only enabling "Start preloading immediately"
and adding the above rule.*
   Then just go to https://store.steampowered.com/app/952060/RESIDENT_EVIL_3/ 
   and mouseover any of the image thumbs:
   ![2020-03-18_201007](https://user-images.githubusercontent.com/723651/76992882-9bc88300-6954-11ea-9f50-62da09599f29.jpg)

3. Just one note: I see that that setting MPIV's `run-at` via the script manager's script settings to `document-start` only works in VM: In TM the script it stops working.

**Comment by tophf** [comment]
Should be fixed now.

**Comment by darkred** [comment]
It works fine. Thanks a lot!

**Comment by darkred** [comment]
Could we please add captions (`c`) to the built-in facebook rule?

Adding `c: '._2vj8'` below line 1372 of the script seems to work ok

https://github.com/tophf/mpiv/blob/752769ed8ec214494e6eab0d65021e2ef2fafb64/script.user.js#L1372 

Example gallery: https://www.facebook.com/pg/instagram/photos/

**Comment by tophf** [comment]
I don't have an account there so FB is serving a different page to me where there is no `._2vj8` but even if it was present, such names are randomly generated and they change every now and then, updating them in a built-in rule would be a constant PITA.

**Comment by darkred** [comment]
OK, I understand. This was my worry too, that this seemingly random selector name could change at anytime.

---

<details>
<summary>Not that it matters, but just a clarification to my previous post:</summary>

Regarding this:
> I don't have an account there so FB is serving a different page to me where there is no `._2vj8`


That element exists (also without login to fb) **only when there are captions for the image**:
e.g. for the 4th thumbnail link of the test gallery,
that link gets converted by the built-in rule to "**mbasic**.facebook.com":
https://mbasic.facebook.com/instagram/photos/a.372558296163354/2813519825400510/?type=3
In the above page, the `._2vj8` exists.
</details>

**Comment by darkred** [comment]
I'd like to report an issue and make a suggestion, please:

Issue:
(using latest `master` of script in TM/VM)
**None of the 3 built-in rules for deviantart.com seem to work anymore.**

I also tried adding `,a[data-hook=deviation_link]` to the `e` property 
of the custom rule in https://w9p.co/userscripts/mpiv/manage_rules.html?edit=39,
but there not even logging entry in console when I mouseover on any thumb on the test pages below.

Test pages: 
https://www.deviantart.com/
https://www.deviantart.com/topic  (and open any link a new page)
https://www.deviantart.com/daily-deviations  <--

In the 3rd link there is an actual rule match: the built-in `u: ',strp/',`
but it fails with "File can't be displayed".

If I may help anymore with more info, please ask.

---

Suggestion:
I quote from the MPIV settings:
> To disable, put any symbol except a..z 0..9 - .
> in "d" value, for example "d":"!foo.com"

So, could you please make it so, such **disabled rules**, to be displayed (both as listed, or when you do a search ) in MPIV settings as **grayed out**, in order to visually distinguish them?

**Comment by tophf** [comment]
I've switched deviantart to `q` mode because I couldn't find a way to transform the `strp` links: lots of them won't work even if I keep token in the URL.

>disabled rules

Start the rule with "d" and add that symbol to the beginning so you'll see it immediately and the rules will be sorted automatically e.g. `{"d":"~foo", ........}`.

**Comment by darkred** [comment]
Thank you for deviantart.

Regarding disabled rules, yes, I always start my rules with `"d"`,
and yes, I know they are sorted automatically, that's very useful.
But, what I have in mind is: 
as you type a non-`a..z 0..9 - .` symbol in `"d"` that disables it, 
its font color to **immediately become grayed out**, 
*similar to the entire custom rule row currently becoming red if you type a symbol that makes the rule invalid.*

**Comment by tophf** [comment]
I understand the idea, I'm just reluctant to add such a feature as I want to keep the userscript code size small.

**Comment by darkred** [comment]
I certainly understand and admire your effort for keeping the performance of the script optimal.
I just believe that the feature I ask is worth the "overhead" (hope I'm using the right word) because: 
- it will make the non-disabled custom rules visually stand out (both as a list and when searching), 
- and, even more worth, knowing that the custom rule you've clicked and are trying to edit/fix/improve, it won't work again no matter what, unless you remove the non-`a..z 0..9 - .` symbols in their `"d"` property *(it happens to me very often)*

**Comment by tophf** [comment]
Okay, the second point convinced me.

**Comment by darkred** [comment]
Thanks so much, it works great!

**Comment by darkred** [comment]
Hi @tophf 

I've noticed the following issue with the latest commits after 1.1.11 and on:
if I have Start preloading immediately" enabled, sometimes the image in the popup gets stuck.

STR
- Tested with a fresh Chrome profile, with only TM/VM and the script 1.1.12 installed,
and only enabling "Start preloading immediately",
- open Chrome 'Network' devtool and check/click "Disable cache" 
- go to https://old.reddit.com/r/marvelstudios/
- move mouse quickly up and down hovering on various post image thumbnails in the left side of the page:
- notice that sooner or later, one of the displayed images in the popup will be stuck, 
and you have to reload the page.

[Screen capture](https://github.com/tophf/mpiv/files/4606825/Video_2020-05-11_011116.zip) (4.3MB zipped wmv)

**Comment by tophf** [comment]
I think I've probably fixed it yesterday in 4bbead34, try the new master code.

**Comment by darkred** [comment]
Yes, it's fixed, thank you!

---

By the way, I'd like to make a suggestion for the repo, to avoid such cases(=that the reporter hasn't checked the latest master code) in the future:
to add the following in the New Issue template :

```
<!--

When reporting problems, always make sure you have tested the latest master code first, i.e. https://github.com/tophf/mpiv/raw/master/script.user.js
Your issue might have already been fixed.

-->
```

To facilitate you, I thought of making a PR for your repo
with the above content as this new file: `.github/ISSUE_TEMPLATE.md` ,
(as I have done with [my repo](https://github.com/darkred/Userscripts/blob/master/.github/ISSUE_TEMPLATE.md) based on [this help guide](https://help.github.com/en/github/building-a-strong-community/manually-creating-a-single-issue-template-for-your-repository)) 
but GitHub shows in the above page that it's a legacy, not suggested, workflow:
> You are using an old version of issue templates. Please update to the new issue template workflow. [Learn more](https://help.github.com/articles/about-issue-and-pull-request-templates)

**Comment by tophf** [comment]
I simply didn't push the commit until after your report. I know about issue templates and I'll use them in some distant future when I'm flooded by reports :-)

**Comment by darkred** [comment]
Ok, then! 👍
You see, I was almost 100% certain that there were no newer commits when I made the STR in my report, and I just couldn't explain how that new commit had missed my attention!

**Comment by darkred** [comment]
Unfortunately, the issue still occurs, even after the very latest commit https://github.com/tophf/mpiv/commit/b7aa281b8ec9396de0363cb3827b4b3270a661bd .
The issue doesn't occur consistently with a specific image, it happens randomly,
but sooner or later it will surely happen.
(the example below happened to me within just 1 minute, in a fresh browser profile)

STR 
- enable "Start preloading immediately"
- go to https://old.reddit.com/ and hover quickly over the thumbnails to the left:
at some point, and image in popup will stay there and never close.

[Screenshot](https://user-images.githubusercontent.com/723651/81839828-c435bd80-9550-11ea-88d1-00f8b7952cd5.jpg)


I got this error at the time of the screenshot :
![2020-05-13_193033](https://user-images.githubusercontent.com/723651/81839857-cf88e900-9550-11ea-8ac4-4647b49a7d63.jpg)

**Comment by darkred** [comment]
And, it happened to me, in my main profile, after I made the last comment:

the stuck images are now 2 !!

[screenshot](https://user-images.githubusercontent.com/723651/81842220-52f80980-9554-11ea-8b4b-4873e46f47de.jpg)

**Comment by tophf** [comment]
Well I can't reproduce it so the only other way to fix it is to keep guessing (try the new master branch) or to fully rewrite the core logic which is currently based on the original so it became convoluted/fragile.

**Comment by darkred** [comment]
Unfortunately I can't provide a consistent STR, I'm sorry about that,
but getting stuck images is happening all the time for me.

&nbsp;

But, if I'm not mistaken, you don't have the "Start preloading immediately" option enabled, right?
If yes, then maybe remove the "Start preloading immediately" option (and the related code) altogether, if it's something that by its nature can make the script work unexpectedly
( preloading the image immediately on mouse hover)?

I mean, the way I see it, trying to display partially-loaded images can cause various problems,
bad ratio, stuck images in the popup, etc

---

For reference, [here](https://greasyfork.org/en/forum/discussion/1595/x) is the related discussion on the original MPIV 
where its author was negative on the initial feature request:

> Preloading of all images will definitely not happen. Too much work and potential to mess things up.

and agreed on wOxxOm 's suggested approach for single images only.

**Comment by tophf** [comment]
I've tested with the option enabled.
Do you see the same with the new 46023210?

**Comment by darkred** [comment]
Yes, unfortunately. It occured within a few seconds.

(created another fresh Chrome profile, with the option on)
[Screenshot](https://user-images.githubusercontent.com/723651/81851500-3d89dc00-9562-11ea-9f48-d7cecfb7e69a.jpg)

The errors in Console:
![2020-05-13_214121](https://user-images.githubusercontent.com/723651/81851685-8b064900-9562-11ea-8eab-339d5fc3ad4d.jpg)

**Comment by tophf** [comment]
That's a different error which is not related to the bug, fixed now.

**Comment by darkred** [comment]
Unfortnunately, the issue still occurs.
It doesn't occur consistently, but this time it occured immediately:

I clicked Chrome's Settings|Clear browser data|everything
and reloaded https://old.reddit.com/: 
it occurred literally immediately, while hovering quickly on the very top images:

The two issues occurred together, stuck images + bad ratio:
Bad ratio (the visible image in the screenshot) : 
![2020-05-13_220520](https://user-images.githubusercontent.com/723651/81854126-20efa300-9566-11ea-9297-8ab1abf0abd2.jpg)
and if I rightclick on the image with the bad ratio and click "Delete element" in "Elements" devtool
then the second stuck image becomes visible to the screenshot:
![2020-05-13_220631](https://user-images.githubusercontent.com/723651/81854153-2d73fb80-9566-11ea-90b8-e2d9ed708a13.jpg)

There are no errors in Console.

**Comment by tophf** [comment]
Well, I'll leave the option enabled and hopefully see the bug someday...

**Comment by tophf** [comment]
Might be helpful if you could find the last good commit.

**Comment by tophf** [comment]
Also try the new master branch.

**Comment by darkred** [comment]
I've tried the new master branch,
made a lot of tests, and the issue hasn't occurred again.
I consider it fixed.

_In the bad case it occurs again, I'll try to find the last good commit._

Thanks a lot!

**Comment by darkred** [comment]
Continuing the feature request #28 I'd like to make a relevant suggestion, please:
to add flip horizontally and vertically functionality via keyboard shortcuts <kbd>H</kbd> and <kbd>V</kbd>

These transformations are possible via CSS like this:

```CSS
/* flip horizontally */
img {
  transform: scaleX(-1);
}

/* flip vertically */
img {
  transform: scaleY(-1);
}
```

This is a thing I always wanted from the original mpiv: I always thought that flipping is something that goes together with rotating, they are both useful to have.
I hope you like my suggestion, @tophf !

**Comment by tophf** [comment]
Could you explain in which cases flipping could be useful? Also, I don't like `h` and `v`, I'd like add one hotkey `f` that flips horizontally so to use it vertically one can rotate first.

**Comment by darkred** [comment]
Many images on the internet are self photos, taken in front of a mirror.
Also, there are people that mirror their photos afterwards, because they think that it's better that way (I disagree), e.g. left-handed guitarists. Or car photos (meant for  left/right-hand-drive markets respectively).
And, there are many cases that images that just seem awkward/unnatural/"not quite right" to me, e.g. landspaces,
and when I flip them it becomes apparent that they were mirrored.

**Comment by tophf** [comment]
I see. Then it seems like one hotkey is enough because a vertical flip seems would be a rare thing that can be performed as a horizontal flip plus two rotations. Try the new master branch.

**Comment by darkred** [comment]
Thank you very much !

_<sub>Although I'd prefer a second hotkey, I have to agree with you that doing vertical flips is rare compared to horizontal ones.</sub>_

---

Just one thing I noticed:
If I do 1 rotate (or 3 consecutive rotates) on an image, and then flip it ("F"),
then the flipping that is done is vertical, not horizontal.

Could you please make it do horizontal flipping in these cases ?
I'm asking this because that's the behaviour I'm used to in e.g. IrfanView image viewer,
when doing combinations of rotate (R) + flip horizontal (H) .

**Comment by tophf** [comment]
I don't understand.

**Comment by darkred** [comment]
Take this image link:
[landscape-photography-at-every-hour-part-ii-photographing-landscapes-in-rain-or-shine-683x390](https://user-images.githubusercontent.com/723651/82228343-ac37b280-9931-11ea-964e-412986781940.jpg)

If you hover on that link and press once R and then F
you'll get [this](https://user-images.githubusercontent.com/723651/82228817-4d266d80-9932-11ea-933c-5c875cf36bd5.jpg)

while I'd expect it to become like [this](https://user-images.githubusercontent.com/723651/82228828-50215e00-9932-11ea-8238-01ae89ec8be4.jpg)

**Comment by tophf** [comment]
I understand but I don't see the point. You can simple rotate left or rotate right twice.

**Comment by darkred** [comment]
Yes, I can, but, since there's now only 1 flip hotkey (for horizontal flipping),
it confuses me that, if the image is rotated 90 or 270 degrees, then it does a vertical flipping instead.

I'd expect it to to do horizontal flipping in all cases, because that's the behavior I'm used to (rotating and flipping is something I do quite often in IrfanView).

The way it currently works, in the two cases that I describe, it gives me the wrong impression that there's a 2nd hotkey (for vertical flipping), that I've pressed it by mistake.

**Comment by tophf** [comment]
Okay, I'm convinced. Add `h` and `v`.

**Comment by darkred** [comment]
Thank you so much!

**Comment by darkred** [comment]
Hi there, @tophf 

I've noticed in the latest master (https://github.com/tophf/mpiv/commit/eb84ee40f1419409acba57cdfc4efe4ccaff144c)
that clicking the `Install rule from repository...` (in both TM/VM)
results in:

```
Uncaught (in promise) TypeError: Cannot set property 'hidden' of undefined
    at HTMLAnchorElement.setupRuleInstaller (Mouseover Popup Image Viewer.user.js:2865)
```

Last workign commit: https://github.com/tophf/mpiv/commit/a1cb814f2364480c6e96b8a276d2ffdaffa0bb79

**Comment by tophf** [comment]
Thanks, fixed.

**Comment by darkred** [comment]
Hi @tophf 

I've noticed that there's no keyboard shortcut to freeze the captions as you hover an image.
And holding down <code>Shift</code> (**freeze**) while entering thumbnail, doesn't make the caption itself remain.

<details>
<summary>Currently it disappears after 3 sec:</summary>

URL example: https://www.instagram.com/p/CLj9NDHMhID/

![](https://user-images.githubusercontent.com/723651/108864075-85ae5280-75fa-11eb-9ef7-e11d24513c9b.gif)
</details>

How about adding a new keyboard shortcut, <kbd>s</kbd>, to freeze the caption while pressed?
I'd find it super useful while browsing in instagram.

**Comment by tophf** [comment]
I'd rather make <kbd>Shift</kbd> freeze the bar while it's being pressed rather than adding a new hotkey. How about it?

**Comment by darkred** [comment]
I suggested a different hotkey, thinking the case that someone might want to freeze the image, but not the caption too.
Otherwise, I have no objection in using the existing hotkey, <kbd>Shift</kbd> .

**Comment by tophf** [comment]
Well, let's hope that freezing the info would be helpful in all or most cases :-)

**Comment by darkred** [comment]
Thanks a lot for your quick response, adding this feature!
